pipeline {
    agent any

    // 設定排程：每天早上 8 點自動執行 (Cron 語法)
    triggers {
        cron('54 1 * * *') 
    }

    stages {
        stage('1. Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/okm2629/jenkins.git'
            }
        }

        stage('2. Build Image') {
            steps {
                script {
                    // 確認 "jobs/10_DailyTechNewsArchivist"
                    dir('jobs/10_NewsArchivist') {
                        // 因為已經進入資料夾，現在 "." 就代表該資料夾，能找到 Dockerfile 了
                        sh "docker build -t news-scraper:latest ."
                    }
                }
            }
        }

        stage('3. Run Scraper') {
            steps {
                script {
                    dir('jobs/10_NewsArchivist') {

                        sh "docker run --rm -v \$(pwd):/app/data news-scraper:latest"
                        
                        // (除錯用) 加入這行確認檔案真的有產生
                        sh "ls -l *.csv" 
                    }
                }
            }
        }
        
        stage('4. Archive Results') {
            steps {
                dir('jobs/10_NewsArchivist') {
                    // 使用通配符 *.* 抓取所有的 csv 和 html，這樣不管你檔名怎麼改都抓得到
                    archiveArtifacts artifacts: '*.*', fingerprint: true
                }
            }
        }
    }
}